learning_templates/learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

#template tagging
app_name = 'basic_app'

urlpatterns = [
path('relative/', views.relative, name = 'relative'),
path('other/', views.other, name = 'other'),
path('',views.index,name='index')
]

learning_templates/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name= 'views'),
    path('basic_app/',include('basic_app.urls')),
]

learning_templates/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'Hello World', 'number':123}
    return render(request,'basic_app/index.html', context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_template.html')

learning_templates/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
     <a class="navbar-brand" href="{% url 'basic_app:index' %}">Navbar</a>
     <a class="nav-link" href="{% url 'admin:index' %}">Home <span class="sr-only">(current)</span></a>
     <a class="nav-link" href="{% url 'basic_app:other' %}">Home <span class="sr-only">(current)</span></a>

</div></nav>
      <div class="container">
        {% block body_block %}

        {% endblock %}

      </div>

  </body>
</html>

learning_templates/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% block body_block %}
<h1>Welcome To Index</h1>
<h1>{{ text|cut:'world' }}</h1>
<h1>{{ number|add:"99" }}<h1>
{% endblock %}

learning_templates/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% block body_block %}
<h1>Welcome To Other</h1>
<h2>This is an example of template inheritence</h2>
<h1> {{ text }} </h1>
<h1> {{ number }} <h1>
{% endblock %}

learning_templates/learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h1>Realative Url Template</h1>
<a href="{% url 'basic_app:other' %}"> The other page</a>
  </body>
</html>